# Generated by Django 2.2.7 on 2019-12-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191205_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
